### ISSUE TITLE
TODO list before start of 2019 season

### ISSUE THREAD

**Issue by cja769** [cja769/NFL-Pickem#1]
- [ ] Custom login success handler so that it redirects to where you were trying to go before it forced you to login
- [ ] Do something about team records since it's going off of all of the matchups instead of the current seasons
- [ ] Test locally to make sure that no problems happen when adding matchups for 2019 season
